version: 2
updates:
 # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
  # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows`. You can use `directory: "/"`.)
    directory: /
    schedule:
    # Need to define how often to check for new versions for each package manager. Either daily, weekly, or monthly
      interval: daily

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
      # interval: "weekly"
