name: CD - Integrated Workflow

on:
  workflow_run:
    workflows: "CI - Integrated Workflow"
    types:
      - completed
jobs:
  Deployment:
    uses: ./.github/workflows/harness_deployment.yaml
    with:
      secrets: ${{ secrets }}
      
  selenium:
    uses: ./.github/workflows/scrape.yml

  blazemeter:
    uses: ./.github/workflows/blazemeter.yml
    with:
      secrets: ${{ secrets }}
