name: Build and Harness Deployment
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: dindrunner
    env:
      IMAGE_TAG: ${{ needs['Build and Harness Deployment'].outputs.IMAGE_TAG }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  deploy-dev:
    needs: build
    runs-on: dindrunner
    environment: dev
    if: github.ref == 'refs/heads/feature' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Harness' || github.ref == 'refs/heads/feature_app_insights_test'    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to DEV
      env:
        IMAGE_TAG: ${{ github.run_id }}
        environment: dev
      run: |
        sudo apt-get update -y
        sudo apt install curl -y
        sudo apt-get install python3-pip -y
        sudo pip install requests
        python3 ./.github/scripts/harness_start.py ${{ env.environment }}  ${{ env.IMAGE_TAG }}
  deploy-qa:
    needs: deploy-dev
    runs-on: dindrunner
    environment: qa
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Harness'  || github.ref == 'refs/heads/feature_app_insights_test'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to QA
      env:
        IMAGE_TAG: ${{ github.run_id }}
        environment: qa
      run: |
        sudo apt-get update -y
        sudo apt install curl -y
        sudo apt-get install python3-pip -y
        sudo pip install requests
        python3 ./.github/scripts/harness_start.py ${{ env.environment }}  ${{ env.IMAGE_TAG }}

  deploy-uat:
    needs: deploy-qa
    runs-on: dindrunner
    environment: uat
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Harness'  || github.ref == 'refs/heads/feature_app_insights_test'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to UAT
      env:
        IMAGE_TAG: ${{ github.run_id }}
        environment: uat
      run: |
        sudo apt-get update -y
        sudo apt install curl -y
        sudo apt-get install python3-pip -y
        sudo pip install requests
        python3 ./.github/scripts/harness_start.py ${{ env.environment }}  ${{ env.IMAGE_TAG }}

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Harness'  || github.ref == 'refs/heads/feature_app_insights_test'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to PROD
      env:
        IMAGE_TAG: ${{ github.run_id }}
        environment: prod
      run: |
        sudo apt-get update -y
        sudo apt install curl -y
        sudo apt-get install python3-pip -y
        sudo pip install requests
        python3 ./.github/scripts/harness_start.py ${{ env.environment }}  ${{ env.IMAGE_TAG }}

