name: Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  jfrog:
    runs-on: dindrunner
    steps:
      - name: Set up HashiCorp Vault 
        uses: hashicorp/vault-action@v2 
        with: 
         #Reading secrets from Github secrets 
          url: "${{ secrets.VAULT_URL }}" 
          token: "${{ secrets.VAULT_SECRET }}" 
          tlsSkipVerify: true 
          #Reading secrets from hashicorp vault 
          secrets: | 
            secret/data/githubactions JFROG_REPO |JFROG_REPO;
            secret/data/githubactions JFROG_TOKEN |JFROG_TOKEN;
            secret/data/githubactions JFROG_URL |JFROG_URL;
            secret/data/githubactions JFROG_USERNAME |JFROG_USERNAME;
            
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.JFROG_URL }}
          username: ${{ env.JFROG_USERNAME }}
          password: ${{ env.JFROG_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ env.JFROG_URL }}/${{ env.JFROG_REPO }}/dotnetsample:latest

#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
 #       with:
  #        image-ref: ${{ env.JFROG_URL }}/${{ env.JFROG_REPO }}/dotnetsample:latest
   #       format: 'table'
    #      exit-code: '1'
    #      ignore-unfixed: true
     #     vuln-type: 'os,library'
      #    severity: 'CRITICAL,HIGH'

      - name: Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.JFROG_URL }}/${{ env.JFROG_REPO }}/dotnetsample:latest
